### ISSUE TITLE
JSON data as single object for reflector

### ISSUE THREAD

**Issue by kc1awv** [n7tae/dvin-tools#1]
Fixing a bug in JSON formatting - restructure the data so that the dump from DHT is a single JSON object, with arrays for Peers, Users and Clients.

Bug produces this:
![Screenshot_2022-12-12_13-38-06](https://user-images.githubusercontent.com/43918257/207127939-63368f89-f93b-40ba-8f99-b55436865211.png)

Patched code:
![Screenshot_2022-12-12_13-38-32](https://user-images.githubusercontent.com/43918257/207127977-e72e9500-8e0d-4154-ac3e-555b76dc72e1.png)

**Comment by n7tae** [comment]
Applications will be developed that will only be interested in one section. I think that means that each section needs to be in an independent json object.

**Comment by n7tae** [comment]
Yes, these aren't large sections... But a dht will amplify any i/o request because a lot of other system will be involved. First of all, a node doing a get() won't necessarily get the requested section from the publisher. In fact for a dht with a few hundred reflectors, it will probably be rare that the section will be sent by the publishing node. Secondly, dht-get will eventually be expanded to do a listen() instead of a get. A listen will spawn a new thread and return a section every time there is an update. While the config section won't change at all, the peers can change more frequently and the clients and users will change frequently for a busy reflector. That's wasting bandwidth on the dht for no good reason if a listener is only interested in one section.

**Comment by n7tae** [comment]
The -`s` switch will specify a single section (`c`, `p`, `l` - for *linked client*, or `u`). If there is no `-s`, they you get() all four.

**Comment by n7tae** [comment]
BTW, the beauty of the single section request is that it's done in a dth::Where clause that is executed on the data provider side. All part of the OpenDHT design to be as efficient as possible.

**Comment by kc1awv** [comment]
Right, but getting all four sections with just the `-j` switch doesn't produce a single JSON object - breaking what I am attempting to do with integrating the output into the reflector registry, and/or the reflector dashboards. I'd rather make one call and get all the info in a single object, and load that into a struct for parsing.

You can close this and I'll drop the PR unless you think there's a better solution :smile:

**Comment by n7tae** [comment]
The -j switch is no more. Json output is now the only output. Also gmt time are the default (with the T and Z in the string). Use a `-l` switch for local time.
All four sections (no `-s` switch) come out as `{"Configuration":{...},"Peers":[...],"Clients":[...],"Users":[...]}`, that is an object made up from a "Configuration" object, and a "Peers", "Clients" and "Users" list. If you ask for a reflector that doesn't exist, you get `{}`.
